config/routes.rb
Panka::Application.routes.draw do

  scope '(:locale)' do
    resources :guests, :examinations, :users, :statistics
    resources :images, :only => :show
    get "main/index"
    
    
    controller :users do
      get 'reset_password' => :edit
    end
    
    controller :comments do
      post "comments" => :create
      delete "comments" => :destroy
    end
    
    controller :services do
      get "mark_vip" => :mark_vip
    end
    
    
    
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
      get 'forgot_password' => :show_forgot_password
      post 'forgot_password' => :send_forgot_password
    end

    controller :guests do
      post 'search_guest' => :search
      post 'search_guest_examination' => :search_examination
    end

    controller :exam_search do
      post 'search_exam' => :search
    end
    
    controller :guest_finder do
      post 'find_guest' => :search
    end
    
    controller :examinations do
      post 'exam_images' => :save_image
    end
    
    controller :images do
      delete 'delete_image' => :destroy
      get 'edit_image' => :edit
      put 'exam_image' => :update
    end

  end

  root :to => 'sessions#new'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_filter :check_login
  
  def index
    
  end

end

app/helpers/main_helper.rb
module MainHelper
  
  
end

app/views/main/_header_menu.html.erb
<div id="title">
	<h1>Panka</h1>
	<p>
		<%= t('.title') %>
	</p>
</div>
<div id="menu">
	<% unless session[:user] %>
	<%= link_to t('.registration'), new_user_path %>
	<%= link_to t('.login'), login_path %>
	<% else %>
	<% @user = get_user(session[:user]) %>
	<span class="bold_grey">Hello, <%= @user.username %></span> |
	<%= link_to t('.my_account'), edit_user_path(:id => session[:user]) %> |
	<%= link_to t('.log_out'), logout_path, :method => 'delete' %>
	<div class="last_login">
		Last login: <%= @user.last_login %>
	</div>
	<% end %>
</div>

app/views/main/_navigation_menu.html.erb
<div id="header_menu">
	<ul>
		<li class="first">
			<%= link_to 'Home', main_index_path %>
		</li>
		<li>
			<%= link_to t('.add_guest'), new_guest_path %>
		</li>
		<li>
			<%= link_to t('.guests'), guests_path %>
		</li>
		<li>
			<%= link_to t('.examinations'), examinations_path %>
		</li>
		<li>
			<%= link_to 'Add examination', new_examination_path %>
		</li>
		<% if @user.admin %>
		<li>
			<a href="#">Admin</a>
		</li>
		<% end %>
	</ul>

	<div id="nav_search">
		<%= form_tag find_guest_path do %>
		<%= text_field_tag :search_field, params[:search_field], :placeholder => 'name' %>
		<%= submit_tag 'Search' %>
		<% end %>
	</div>
</div>

app/views/main/index.html.erb
<div class="widget">
	<h4 class="ui-corner-top">Welcome</h4>
	<div class="content">
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>
</div>