config/routes.rb
Panka::Application.routes.draw do

  scope '(:locale)' do
    resources :guests, :examinations, :users, :statistics
    resources :images, :only => :show
    get "main/index"
    
    
    controller :users do
      get 'reset_password' => :edit
    end
    
    controller :comments do
      post "comments" => :create
      delete "comments" => :destroy
    end
    
    controller :services do
      get "mark_vip" => :mark_vip
    end
    
    
    
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
      get 'forgot_password' => :show_forgot_password
      post 'forgot_password' => :send_forgot_password
    end

    controller :guests do
      post 'search_guest' => :search
      post 'search_guest_examination' => :search_examination
    end

    controller :exam_search do
      post 'search_exam' => :search
    end
    
    controller :guest_finder do
      post 'find_guest' => :search
    end
    
    controller :examinations do
      post 'exam_images' => :save_image
    end
    
    controller :images do
      delete 'delete_image' => :destroy
      get 'edit_image' => :edit
      put 'exam_image' => :update
    end

  end

  root :to => 'sessions#new'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :commentable_id, :content, :commentable_type
  belongs_to :commentable, :polymorphic => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    comment = Comment.new(params[:comment])
    comment.save
    if (params[:comment][:commentable_type] == 'Examination')
      redirect_to examination_path(:id => params[:comment][:commentable_id])
    else 
      redirect_to guest_path(:id => params[:comment][:commentable_id])
    end
  end
  
  def destroy
    comment = Comment.find(params[:id])
    comment.delete
    if (params[:commentable_type] == 'Examination') 
      redirect_to examination_path(params[:commentable_id])
    else
      redirect_to guest_path(params[:commentable_id])
    end
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<div class="comment_title ui-corner-top">
		<h4><%= @commentable.user.username %> <%= comment.created_at %></h4>
		<span class="header_icons"><%= link_to 'Delete comment', comments_path(:id => comment.id, :commentable_type => comment.commentable_type, :commentable_id => comment.commentable_id), :method => 'delete', :class => 'ui-icon ui-icon-trash' %> </span>
	</div>
	<div class="content">
		<div>
			<%= comment.content %>
		</div>
	</div>
</div>

app/views/comments/_comments.html.erb
<%= render :partial => 'comments/comment', :collection => @commentable.comments %>

<%= form_for(@comment) do |f| %>
<div class="widget">
	<h4 class="ui-corner-top">Comment</h4>
	<div class="content">
		<%= f.hidden_field :commentable_id, :value => @commentable.id %>
		<%= f.hidden_field :commentable_type, :value => @commentable_type %>
		<div class="field">
			<%= f.text_area :content %>
		</div>
		<div class="actions">
			<%= f.submit :class => 'submit' %>
		</div>
	</div>
</div>
<% end %>