config/routes.rb
Panka::Application.routes.draw do

  scope '(:locale)' do
    resources :guests, :examinations, :users, :statistics
    resources :images, :only => :show
    get "main/index"
    
    
    controller :users do
      get 'reset_password' => :edit
    end
    
    controller :comments do
      post "comments" => :create
      delete "comments" => :destroy
    end
    
    controller :services do
      get "mark_vip" => :mark_vip
    end
    
    
    
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
      get 'forgot_password' => :show_forgot_password
      post 'forgot_password' => :send_forgot_password
    end

    controller :guests do
      post 'search_guest' => :search
      post 'search_guest_examination' => :search_examination
    end

    controller :exam_search do
      post 'search_exam' => :search
    end
    
    controller :guest_finder do
      post 'find_guest' => :search
    end
    
    controller :examinations do
      post 'exam_images' => :save_image
    end
    
    controller :images do
      delete 'delete_image' => :destroy
      get 'edit_image' => :edit
      put 'exam_image' => :update
    end

  end

  root :to => 'sessions#new'

end

app/controllers/exam_search_controller.rb
class ExamSearchController < ApplicationController
  
  def search
    from = params[:from_date]
    to = params[:to_date]
    @examinations = Examination.where(["created_at < ? and created_at > ?", to, from])
  end
end

app/helpers/exam_search_helper.rb
module ExamSearchHelper
end

app/views/exam_search/_search_form.html.erb
<%= form_tag search_exam_path do %>
<div class="form">
	<h4 class="ui-corner-top">Search</h4>
	<div class="content">
		<div class="field">
			<%= text_field_tag :from_date, params[:from_date], :class => 'datepicker' %>
			<label for="from_date" >From date</label>
		</div>
		<div class="field">
			<%= text_field_tag :to_date, params[:to_date], :class => 'datepicker' %>
			<label for="to_date" >To date</label>
		</div>
		<div class="actions">
			<%= submit_tag 'Search', :class => 'submit' %>
		</div>
	</div>
</div>
<% end %>

app/views/exam_search/search.html.erb
<% render 'search_form' %>

<div class="widget ui-corner-top">
	<div class="content ui-corner-top">
		<table width="100%">
			<thead>
				<tr>
					<th><%= t('.datum') %></th>
					<th><%= t('.anamnezis') %></th>
					<th><%= t('.status') %></th>
					<th><%= t('.treatment') %></th>
					<th><%= t('.charge') %></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<%= render :partial => 'examinations/examination', :collection => @examinations %>
		</table>
	</div>
</div>