config/routes.rb
Panka::Application.routes.draw do

  scope '(:locale)' do
    resources :guests, :examinations, :users, :statistics
    resources :images, :only => :show
    get "main/index"
    
    
    controller :users do
      get 'reset_password' => :edit
    end
    
    controller :comments do
      post "comments" => :create
      delete "comments" => :destroy
    end
    
    controller :services do
      get "mark_vip" => :mark_vip
    end
    
    
    
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
      get 'forgot_password' => :show_forgot_password
      post 'forgot_password' => :send_forgot_password
    end

    controller :guests do
      post 'search_guest' => :search
      post 'search_guest_examination' => :search_examination
    end

    controller :exam_search do
      post 'search_exam' => :search
    end
    
    controller :guest_finder do
      post 'find_guest' => :search
    end
    
    controller :examinations do
      post 'exam_images' => :save_image
    end
    
    controller :images do
      delete 'delete_image' => :destroy
      get 'edit_image' => :edit
      put 'exam_image' => :update
    end

  end

  root :to => 'sessions#new'

end

app/models/examination.rb
class Examination < ActiveRecord::Base
  attr_accessible :anamnezis, :charge, :status, :treatment, :guest_id, :user_id
  
  belongs_to :guest
  belongs_to :user
  
  validates :anamnezis, :charge, :guest_id , :status, :treatment, :presence => true
  
  has_many :exam_images
  has_many :comments, :as => :commentable
end

app/controllers/examinations_controller.rb
class ExaminationsController < ApplicationController
  before_filter :check_login
  
  def index
    if (params[:guest_id])
      @examinations = Examination.paginate :page => params[:page], :per_page => 20, :conditions => [ 'user_id = ? and guest_id = ?', session[:user], params[:guest_id]]
    else
      @examinations = Examination.paginate :page => params[:page], :per_page => 20, :conditions => [ 'user_id = ?', session[:user]]
    end
  end

  def new

    begin
      if (params[:guest_id])
        Guest.find(params[:guest_id])
      else
        flash[:alert] = 'Please select a guest first!'
      end

      @examination = Examination.new
      @examination.guest_id = params[:guest_id]
    rescue
      redirect_to main_index_path, :alert => 'There is no guest with this id!'
    end

  end

  def show
    @comment = Comment.new
    @examination = Examination.find(params[:id]);
    if (@examination.guest.user_id != session[:user])
      redirect_to main_index_path, :alert => 'You can not access this page!'
    end
  end

  def create
    examination = Examination.new(params[:examination])
    examination.user_id = session[:user]
    if examination.save
      redirect_to guest_path(:id => examination.guest.id)
    else
      redirect_to new_examination_path(:guest_id => examination.guest_id)
    end

  end

  def destroy
    examination = Examination.find(params[:id])
    examination.delete
    redirect_to guest_path(:id => examination.guest.id)
  end

  def save_image
    image = create_image(params[:exam_image])
    begin
      image.save!
    rescue
      flash[:alert] = 'You can upload only jpg files!'
    end
    redirect_to edit_examination_path(:id => params[:exam_image][:exam_id])
  end

  def edit
    @examination = Examination.find(params[:id])
    @picture = ExamImage.new
    if (@examination.guest.user_id != session[:user])
      redirect_to main_index_path, :alert => 'You can not access this page!'
    end
  end

  def update
    exam = Examination.find(params[:id])

    if exam.update_attributes(params[:examination])
      redirect_to guest_path(:id => exam.guest.id)
    else
      redirect_to edit_examination_path(:id => params[:id])
    end
  end


  private 
  
  def create_image image_param
    image = ExamImage.new
    image.examination_id = image_param[:exam_id]
    image.image = image_param[:exam_image]
    image.caption = image_param[:caption]
    image
  end
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/views/examinations/_examination.html.erb
<tr>
	<td><%= link_to examination.updated_at, examination_path(:id => examination.id) %></td>
	<td><%= examination.anamnezis %></td>
	<td><%= examination.status %></td>
	<td><%= examination.treatment %></td>
	<td><%= examination.charge %></td>
	<td><%= link_to 'Edit', edit_examination_path(:id => examination.id), :class => 'ui-icon ui-icon-pencil' %></td>
	<td><%= link_to 'Delete', examination_path(:id => examination.id), :method => 'delete', :confirm => t('.are_you_sure'), :class => 'ui-icon ui-icon-trash' %></td>
</tr>

app/views/examinations/_form.html.erb
<%= form_for(@examination) do |f| %>
<div class="form">
	<h4 class="ui-corner-top">Edit examination</h4>
	<div class="content">
		<% unless @examination.guest_id %>
			<p><%= link_to 'Select guest', guests_path(:mode => 'select', :from => new_examination_path) %></p>
		<% else %>
		<p>Examination for <%= @examination.guest.name %></p>
		<%= f.hidden_field :guest_id, :value => @examination.guest_id %>
		<div class="field">
			<%= f.text_field :anamnezis %>
			<%= f.label t('examinations.anamnezis') %>
		</div>
		<div class="field">
			<%= f.text_field :status %>
			<%= f.label t('examinations.status') %>
		</div>
		<div class="field">
			<%= f.text_area :treatment %>
			<%= f.label t('examinations.treatment') %>
		</div>
		<div class="field">
			<%= f.text_field :charge %>
			<%= f.label t('examinations.charge') %>
		</div>
		<div class="actions">
			<%= f.submit :class => 'submit' %>
		</div>
		<% end %>
	</div>
</div>
<% end %>

app/views/examinations/_image.html.erb
<div class="exam_image">
	<%= link_to (image_tag (image.image.thumb.url)), image_path(:id => image.id), :title => image.caption %>
	<div class="edit">
		<%= link_to 'edit', edit_image_path(:id => image.id), :class => 'ui-icon ui-icon-pencil' %>
	</div>
	<div class="delete">
		<%= link_to 'Delete picture', delete_image_path(:id => image.id, :exam_id => params[:id]), :method => 'delete', :class => 'ui-icon ui-icon-trash' %>
	</div>
</div>

app/views/examinations/edit.html.erb
<%= render 'form' %>
<hr />
<div class="form">
	<%= form_for(@picture) do |f| %>
	<h4 class="ui-corner-top">Upload picture</h4>
	<div class="content">
		<%= f.hidden_field :exam_id, :value => params[:id] %>
		<div class="field">
			<%= f.file_field :exam_image %>
			<%= f.label 'exam_image' %>
		</div>
		<div class="field">
			<%= f.text_field :caption %>
			<%= f.label :caption %>
		</div>
		<div class="actions">
			<%= f.submit :class => 'submit', :value => "Upload" %>
		</div>
	</div>
	<% end %>
</div>
<div class="widget">
	<h4 class="ui-corner-top">Images</h4>
	<div class="content">
		<%= render :partial => 'image', :collection => @examination.exam_images %>
	</div>
</div>

app/views/examinations/index.html.erb
<%= render 'exam_search/search_form' %>

<div class="widget">
	<h4 class="ui-corner-top">Examinations</h4>
	<div class="content">
		<table width="100%">
			<thead>
				<tr>
					<th><%= t('examinations.date') %></th>
					<th><%= t('examinations..anamnezis') %></th>
					<th><%= t('examinations.status') %></th>
					<th><%= t('examinations..treatment') %></th>
					<th><%= t('examinations..charge') %></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<%= render :partial => 'examination', :collection => @examinations %>

		</table>
	</div>
	<%= will_paginate @examinations %>
</div>

app/views/examinations/new.html.erb
<%= render 'form' %>

app/views/examinations/show.html.erb
<div class="widget ui-corner-top">

	<h4 class="ui-corner-top"><%= link_to @examination.guest.name, guest_path(:id => @examination.guest.id) %></h4>
	<div class="content">
		<div>
			<span><%= t(".last_modified") %></span>
			<span><%= @examination.updated_at %></span>
		</div>
		<div>
			<span><%= t(".created_at") %></span><span><%= @examination.created_at %></span>
		</div>
		<div>
			<span><%= t(".anamnezis") %></span>
			<span><%= @examination.anamnezis %></span>
		</div>
		<div>
			<span><%= t(".status") %></span>
			<span><%= @examination.status %></span>
		</div>
		<div>
			<span><%= t(".treatment") %></span>
			<span><%= @examination.treatment %></span>
		</div>
		<div>
			<span><%= t(".charge") %></span>
			<span><%= @examination.charge %></span>
		</div>
<div class="button_row">
		<%= link_to 'Delete examination', examination_path(:id => @examination.id), :class => 'button', :method => 'delete', :confirm => t("are_you_sure") %> <%= link_to 'Edit', edit_examination_path(:id => @examination.id), :class => 'button' %>
	</div>
	</div>
</div>
<% @commentable = @examination %>
<% @commentable_type = 'Examination' %>
<%= render 'comments/comments' %>

<div class="widget">
	<h4 class="ui-corner-top">Images</h4>
	<div class="content">
		<%= render :partial => 'image', :collection => @examination.exam_images %>
	</div>
</div>